/**
 * Fixed reference data for the outreach form — Pillar -> Channel taxonomy,
 * Outreach Mode, and the curated Activity list. Static because this is
 * agreed-upon reference data, not something admins edit at runtime; keeping
 * it in code avoids a lookup table + fetch for values that never change.
 */

export const PILLAR_CHANNELS: Record<string, string[]> = {
  "Government Institutions": [
    "Ministry/Department of Education",
    "Directorate of Technical Education",
    "RTO Centre",
    "State Rural Livelihood Mission (NRLM/SRLM)",
    "Women & Child Development Department",
    "District Collector / DM Office",
    "Skill Development Department",
    "National Skill Development Corporation (NSDC) ecosystem",
    "Rural Self Employment Training Institutes (RSETI)",
    "Health department",
    "Social welfare department",
    "Tribal welfare department",
    "Minority welfare department",
    "Backward classes welfare department",
    "Zilla Parishad / district panchayat",
    "Gram Panchayat network",
    "Employment exchange",
    "Model Career Centres",
    "Directorate of higher education",
    "Municipality / Corporations",
  ],
  "Educational Institutions": [
    "School - (CBSE/ICSE)",
    "School - State Board",
    "School - Kendriya Vidyalaya",
    "School - Jawahar Navodaya Vidyalaya",
    "School - Sainik school",
    "School - Eklavya Model Residential School (EMRS)",
    "School - Kasturba Gandhi Balika Vidyalaya (KGBV)",
    "School - Government residential school",
    "School - Girls school",
    "School - Private school",
    "School - Aided school",
    "Pre-university college (PUC) / junior college",
    "Government degree college",
    "Private degree college",
    "Women's college",
    "Engineering college",
    "Vocational training institute",
    "Skill training institute",
    "Medical & allied science college",
    "University - Central university",
    "University - State university",
    "University - Private university",
    "University - Deemed university",
    "Open university",
    "Distance education institution",
    "Coaching institute - competitive exams",
    "Coaching institute - aviation",
    "Career counselling centre",
    "Student clubs/associations",
  ],
  "Community & Development Institutions": [
    "SHG Network (NRLM/Sanjeevini Cluster)",
    "Anganwadi Centre (AWC)",
    "Panchayat / Gram Sabha",
    "NGO / CBO",
    "Common Service Centre (CSC)",
    "Field Functionary Network (ASHA/AWW/CRP)",
    "Adolescent girls groups",
    "Community resource person (CRP) network",
    "Rotary club",
    "Lions club",
    "Youth associations",
    "Professional volunteer networks",
    "Faith-based/community organisations",
    "SHG network - CLF/GPLF federation network",
    "Alumni volunteer groups",
  ],
  "Strategic Networks": [
    "Women Pilot Association",
    "Aviation Training Academy",
    "CSR / Corporate Partner Network",
    "Industry Body",
    "Sector Skill Council",
  ],
  "Digital Outreach": [
    "Bulk WhatsApp",
    "Bulk Email",
    "Social Media - Instagram",
    "Social Media - Facebook",
    "Social Media - LinkedIn",
    "Digital Influencer Network",
    "Paid Digital Ads",
    "Programme Website / Microsite",
    "Scholarship & Career Platform",
    "SMS Gateway",
  ],
  "Media & Public Relations": [
    "Online News Platform / Digital News Portal",
    "Print Newspaper / Magazine",
    "Television",
    "Radio",
  ],
};

export const OUTREACH_PILLARS = Object.keys(PILLAR_CHANNELS);

export const OUTREACH_MODES = ["Physical", "Digital", "Virtual", "Hybrid", "Media"];

export const OUTREACH_ACTIVITIES = [
  "Official email",
  "Telephonic Discussion",
  "Student WhatsApp circulation",
  "Official meeting",
  "Official circular dissemination",
  "Social media promotion/ Posting",
  "Institutional network cascade",
  "WhatsApp circulation",
  "Website listing",
  "Awareness Session - Students",
  "Email circulation",
  "Awareness session - Faculty",
  "Notice board display",
  "Flyer distribution",
  "MoU/LoU signing",
  "Press release",
  "Digital news coverage",
  "Newspaper article",
  "Media interview",
  "Television interview",
  "Radio spot",
  "Webinar session",
  "Social media posting",
  "Community awareness meeting",
  "Story/reel posting",
];

/** Sentinel value used by "Other (specify)" options to reveal a free-text fallback input. */
export const OTHER_VALUE = "__other__";
