-- Seed data for lookup tables + teams, extracted from Data Validation Sheet.

insert into teams (name, slug) values
  ('BC IGWF Outreach', 'bc-igwf-outreach'),
  ('BC Other Team', 'bc-other-team'),
  ('BC Livelihood Team', 'bc-livelihood-team'),
  ('CB Impact Practice', 'cb-impact-practice'),
  ('BC NE Outreach', 'bc-ne-outreach'),
  ('BC FutureTech', 'bc-futuretech'),
  ('BC KA Outreach', 'bc-ka-outreach'),
  ('CB PCM Team', 'cb-pcm-team'),
  ('Gov Outreach & Partnerships', 'gov-outreach-partnerships');

insert into statuses (code, meaning, sort_order) values
  ('Planned', 'Institution identified and included in outreach plan', 0),
  ('Contact Details Pending', 'Institution identified but contact details not available', 1),
  ('Contact Identified', 'Contact person details collected', 2),
  ('Outreach Request sent', 'Email / letter / WhatsApp / call made', 3),
  ('Approval Awaited', 'Request  submitted, awaiting approval', 4),
  ('Approved', 'Institution approved outreach activity', 5),
  ('Rejected', 'Institution declined participation', 6),
  ('Activity Scheduled', 'Outreach activity date confirmed', 7),
  ('Activity Completed', 'Outreach activity successfully conducted', 8),
  ('No Response', 'No response despite follow-ups', 9),
  ('Closed', 'All planned activities completed and reported', 10);

insert into regions_states (region, state) values
  ('North', 'Delhi'),
  ('North', 'Haryana'),
  ('North', 'Punjab'),
  ('North', 'Himachal Pradesh'),
  ('North', 'Uttarakhand'),
  ('North', 'Uttar Pradesh'),
  ('North', 'Rajasthan'),
  ('North', 'Chandigarh'),
  ('North', 'Jammu & Kashmir'),
  ('North', 'Ladakh'),
  ('South', 'Karnataka'),
  ('South', 'Kerala'),
  ('South', 'Tamil Nadu'),
  ('South', 'Andhra Pradesh'),
  ('South', 'Telangana'),
  ('South', 'Puducherry'),
  ('South', 'Lakshadweep'),
  ('South', 'Andaman & Nicobar Islands'),
  ('East', 'Bihar'),
  ('East', 'Jharkhand'),
  ('East', 'Odisha'),
  ('East', 'West Bengal'),
  ('West', 'Maharashtra'),
  ('West', 'Gujarat'),
  ('West', 'Goa'),
  ('West', 'Dadra & Nagar Haveli and Daman & Diu'),
  ('Central', 'Madhya Pradesh'),
  ('Central', 'Chhattisgarh'),
  ('North-East', 'Assam'),
  ('North-East', 'Arunachal Pradesh'),
  ('North-East', 'Manipur'),
  ('North-East', 'Meghalaya'),
  ('North-East', 'Mizoram'),
  ('North-East', 'Nagaland'),
  ('North-East', 'Sikkim'),
  ('North-East', 'Tripura');

insert into institution_types (category, type) values
  ('Educational Institution', 'Kendriya Vidyalaya (KV) School'),
  ('Educational Institution', 'Navodaya Vidyalaya (JNV)'),
  ('Educational Institution', 'CBSE School'),
  ('Educational Institution', 'ICSE School'),
  ('Educational Institution', 'State Board School'),
  ('Educational Institution', 'Residential School'),
  ('Educational Institution', 'Girls'' School'),
  ('Educational Institution', 'Junior College / PU College'),
  ('Educational Institution', 'Degree College'),
  ('Educational Institution', 'Women''s College'),
  ('Educational Institution', 'Science College'),
  ('Educational Institution', 'Engineering College'),
  ('Educational Institution', 'Polytechnic College'),
  ('Educational Institution', 'Aviation College'),
  ('Educational Institution', 'University'),
  ('Educational Institution', 'Deemed University'),
  ('Educational Institution', 'Private University'),
  ('Educational Institution', 'Central University'),
  ('Educational Institution', 'State University'),
  ('Educational Institution', 'Flying Training Organisation (FTO)'),
  ('Educational Institution', 'Coaching Institute'),
  ('Educational Institution', 'Skill Development Centre'),
  ('Government Agency', 'Department of Education'),
  ('Government Agency', 'Department of Women & Child Development'),
  ('Government Agency', 'Department of Skill Development'),
  ('Government Agency', 'Department of Higher Education'),
  ('Government Agency', 'State Livelihood Mission (SRLM)'),
  ('Government Agency', 'National Rural Livelihood Mission (NRLM)'),
  ('Government Agency', 'District Administration'),
  ('Government Agency', 'District Education Office'),
  ('Government Agency', 'Block Education Office'),
  ('Government Agency', 'Panchayat Raj Institution'),
  ('Government Agency', 'Municipal Corporation'),
  ('Community Institution', 'Anganwadi Centre'),
  ('Community Institution', 'Self-Help Group (SHG)'),
  ('Community Institution', 'SHG Federation'),
  ('Community Institution', 'Village Organisation'),
  ('Community Institution', 'Cluster Level Federation (CLF)'),
  ('Community Institution', 'Community Resource Centre'),
  ('Other', 'Other'),
  ('NGO / Civil Society', 'NGO'),
  ('NGO / Civil Society', 'Community-Based Organisation (CBO)'),
  ('NGO / Civil Society', 'Foundation / Trust'),
  ('NGO / Civil Society', 'Women''s Organisation'),
  ('NGO / Civil Society', 'Youth Organisation'),
  ('Corporate / Industry', 'Corporate CSR Foundation'),
  ('Corporate / Industry', 'Industry Association'),
  ('Corporate / Industry', 'Chamber of Commerce'),
  ('Corporate / Industry', 'Aviation Industry Partner'),
  ('Professional Network', 'Women Pilot Association'),
  ('Professional Network', 'Alumni Association'),
  ('Professional Network', 'Professional Society / Network'),
  ('Media & Digital', 'Media House'),
  ('Media & Digital', 'Scholarship Portal'),
  ('Media & Digital', 'Career Portal'),
  ('Media & Digital', 'Digital Community Platform');
